# Generated by Django 4.2.7 on 2023-12-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hombre',
            name='apellido',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mujer',
            name='apellido',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='niño',
            name='apellido',
            field=models.CharField(max_length=30),
        ),
    ]
